import numpy as np
import os, sys
import argparse
from psgeom import camera, sensors
from btx.interfaces.psana_interface import PsanaInterface

def modify_crystfel_header(input_file, output_file):
    """
    Modify the header of a psgeom-generated Crystfel (.geom) file,
    specifically 1. uncommenting lines indicating the mask file and 
    LCLS parameters and 2. adding entries indicating the location of
    peaks in the cxi files.
    
    Parameters
    ----------
    input_file : str
        input .geom file generated by psgeom
    output_file : str
        output modified .geom file
    """
    outfile = open(output_file, "w")

    with open(input_file, "r") as infile:
        for line in infile.readlines():

            # uncomment by removing semicolon and space
            if line[0] == ';':
                if line.split()[1] in ['clen', 'photon_energy', 'adu_per_eV', 'mask', 'mask_good', 'mask_bad']:
                    outfile.write(line[2:]) 
                else:
                    outfile.write(line)

            # add these header lines for latest crystfel
            elif 'data = /entry_1/data_1/data' in line:
                outfile.write(line)
                outfile.write('\n')
                outfile.write('peak_list = /entry_1/result_1\n')
                outfile.write('peak_list_type = cxi\n')

            else:
                outfile.write(line)

    outfile.close()
    
def generate_geom_file(exp, run, det_type, input_file, output_file, det_dist=None):
    """
    Generate a Crystfel .geom file from either a psana .data or another
    Crystfel .geom file and set the coffset field for each panel based 
    on the estimated detector distance:
        coffset [m] = 1e-3 * (distance - clen)
    Supplying det_dist will override the value pulled from the deployed
    geometry for this run, which is used to compute the coffset parameter.
    
    Parameters
    ----------
    exp : str
        experiment name
    run : int
        run number
    det_type : str
        detector name
    input_file : str
        input .geom or .data file
    output_file : str
        output .geom file
    det_dist : float
        estimated sample-detector distance in mm
    """
    if 'CsPad' in det_type:
        sys.exit("Currently this function does not support the CsPad detector")
    
    if input_file.split('.')[-1] == 'data':
        geom = camera.CompoundAreaCamera.from_psana_file(input_file)
    elif input_file.split('.')[-1] == 'geom':
        if det_type == 'epix10k2M':
            geom = camera.CompoundAreaCamera.from_crystfel_file(input_file, element_type=sensors.Epix10kaSegment)
        else:
            geom = camera.CompoundAreaCamera.from_crystfel_file(input_file)
            
    psi = PsanaInterface(exp=exp, run=run, det_type=det_type)
    if det_dist is None:
        det_dist = psi.estimate_distance()
    coffset = (det_dist - psi.get_clen()) / 1000.
    
    geom.to_crystfel_file(output_file, coffset=coffset)
    
    
#### For command line use ####
            
def parse_input():
    """
    Parse command line input.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--exp', help='Experiment name', required=True, type=str)
    parser.add_argument('-r', '--run', help='Run number', required=True, type=int)
    parser.add_argument('-d', '--det_type', help='Detector name, e.g epix10k2M or jungfrau4M',  required=True, type=str)
    parser.add_argument('-o', '--output_file', help='Output Crystfel geom file', required=True, type=str)
    parser.add_argument('-i', '--input_file', help='Tag to append to cxi file names', required=False, type=str, default='')
    parser.add_argument('--det_dist', help='Estimated distance between sample and detector in mm', required=False, type=float)
    
    return parser.parse_args()

if __name__ == '__main__':
    
    params = parse_input()
    temp_file = os.path.join(os.path.dirname(params.input_file), 'temp.geom')
    generate_geom_file(params.exp, params.run, params.det_type, params.input_file, temp_file, det_dist=params.det_dist)
    modify_crystfel_header(temp_file, params.output_file)
    os.remove(temp_file)
    print(f"CrystFEL geometry file saved to {params.output_file}")
